# Author: Selene Banuelos
# Date: 9/2/2026
# Description: Clean raw dried blood spot EDXRF data from PEARLS participants
# These data were generated by Aaron Specht's lab group

# setup
library(dplyr)
library(janitor)
library(stringr)
library(tidyr)

# import data ------------------------------------------------------------------
# raw EDXRF data
raw <- read.csv('data-raw/Blood Spots Rose 8-20-2026.csv')

# list of specimen IDs sent to Specht lab
original_list <- read.csv('data-raw/DBS Lead pilot specimenID list.csv')

# PEARLS plasma data IDs (links PEARLS IDs to specimen IDs)
pearls <- read.csv('data-raw/PEARLSBio-Plasma_DATA_2023-06-28_1451.csv')

# create column with element symbols -------------------------------------------
# helper function that fills vector with element symbols
fill_in <- function(x){
    
    # find first non-empty string position in vector
    first_element <- min(which(x != ''))
    
    # create new vector that will have filled-in element symbols
    filled_x <- x
    
    # replace empty strings with element symbols
    for(i in first_element:length(x)) {
        # starting at first non-empty index (first element symbol), 
        filled_x[i] <- ifelse(x[i] == '', # if position in OG vector is empty string
                              # replace with element symbol from previous position
                              filled_x[i-1], 
                              # else, keep current element symbol from OG vector
                              x[i] 
                              )
    }
    
    return(filled_x)
}
    
# create vector of element symbol
elements <- names(raw) %>% # get element symbols from column names
    # change items that don't correspond to an element symbol to empty string
    gsub('X.*', '', .) %>%
    # fill empty strings with element symbols
    fill_in(.)

# get variable names from 1st row of dataframe
var_names <- as.character(raw[1,]) %>%
    # strip empty strings from variable names
    str_trim(.)

# combine element symbols with variable names
var_element <- paste(var_names, elements, sep = '_')

# vector of elements without back-calculated concentrations
no_conc <- unique(elements) %>%
    # remove empty empty elements
    stringi::stri_remove_empty(.) %>%
    # extract elements that don't have back-calculated concentrations
    setdiff(., # all elements
            c('Pb', 'As', 'Cd', 'Hg') # elements with back-calculated conc
            )

# clean up format of raw data 
clean <- raw %>%
    # set var_element vector as new column names
    setNames(var_element) %>%
    # remove first row, which contains old variable names
    # and remove last 2 rows with average and SD of data
    slice(2:(nrow(.)-2)) %>%
    # remove columns with row number and 'Seq', which is the same for all obs
    select(-c(Nr_, Seq_)) %>%
    # remove any columns corresponding to Vanadium, since no intensity was 
    # recorded for this element
    select(-contains('_V')) %>%
    # make data longer for storage
    pivot_longer(cols = contains(c('Iraw_', 'Inet_', 'C_', 'Unit_')),
                 names_to = c('.value', 'element'),
                 names_sep = '_'
    ) %>%
    pivot_longer(cols = c(Iraw, Inet, C),
                 names_to = 'measure',
                 values_to = 'value'
    ) %>%
    # remove concentration rows for elements with intensity only
    filter(!(element %in% no_conc & measure == 'C')) %>%
    # clean up variable names
    clean_names() %>%
    # isolate ID numbers used during experimental run
    mutate(specimenid = ident %>%
               # remove 'ROSIE' prefix and any number of 0's before specimen ID 
               # and remove '-2' suffix from any samples run in duplicate
               str_remove_all('^ROSIE0*|-2') %>%
               # remove all whitespaces
               str_remove_all('\\s+') %>%
               # convert from char to numeric
               as.numeric()) %>%
    # remove all whitespaces from experimental IDs & rename to 'expid'
    mutate(expid = ident %>% str_remove_all('\\s+')) %>%
    select(-ident)

# link specimen IDs with PEARLS IDs --------------------------------------------
# check that all the IDs used in experimental run match up with list of IDs that
# was sent with samples
setdiff(unique(clean$specimenid), original_list$specimenID) 
# experimental IDs has ID: 438

setdiff(original_list$specimenID, unique(clean$specimenid)) 
# original list sent has ID: 439

# change specimen ID 438 in EDXRF data to correct specimen ID of 439
clean[clean$specimenid == 438, 'specimenid'] <- 439
clean[clean$expid == 'ROSIE000438', 'expid'] <- 'ROSIE000439'

# link up EDXRF data with PEARLS ID, by specimenid
linked <- pearls %>%
    select(subjectid, specimenid) %>%
    rename(pearls_id = subjectid) %>%
    right_join(., clean, by = 'specimenid') %>%
    # rearrange to show all IDs in first few columns
    select(pearls_id, specimenid, expid, everything()) 

# indicate LODs ----------------------------------------------------------------
# create indicator that specifies if concentrations are above or equal to limit 
# of detection (LOD) for Pb, As, Hg that is reported in 
# Greier et al. 2026 (from Specht lab)
# Pb LOD: 14.14 ug/L
# As LOD: 2.30 ug/L
# Hg LOD: 3.60 ug/L
lods <- linked %>%
    mutate(value = as.numeric(value),
           lod_ugL = case_when(
               # indicators of concentrations >= LOD 
               measure == 'C' & element == 'Pb' & value >= 14.14 ~ 1,
               measure == 'C' & element == 'Pb' & value < 14.14 ~ 0,
               measure == 'C' & element == 'As' & value >= 2.3 ~ 1,
               measure == 'C' & element == 'As' & value < 2.3 ~ 0,
               measure == 'C' & element == 'Hg' & value >= 3.6 ~ 1,
               measure == 'C' & element == 'Hg' & value < 3.6 ~ 0,
               # elements other than Pb, As, Hg don't have LODs reported in Greier
               # Inet and Iraw intensities don't have LOD
               .default = NA))

# output -----------------------------------------------------------------------
# save data as csv file
write.csv(lods, 'data-processed/PEARLS-blood-edxrf.csv', row.names = FALSE)